CREATE TABLE [dbo].[Cotizacion] (
	[Id] INT PRIMARY KEY IDENTITY,
	[ClienteId] INT NOT NULL,
	[NumeroCotizacion] VARCHAR(15) NOT NULL,
	[Monto] DECIMAL(18, 2) NOT NULL,
	[Descuento] DECIMAL(18, 2) NOT NULL,
	[Impuesto] DECIMAL(18, 2) NOT NULL,
	[TipoComprobanteId] INT NOT NULL,
	[Comprobante] VARCHAR(8) NOT NULL,
	[Nota] VARCHAR(100) NOT NULL,
	[LlevaEnvio] BIT NOT NULL,
	[LlevaInstalacion] BIT NOT NULL,
	[UsuarioCreacionId] INT NOT NULL,
	[DireccionId] INT NULL,
	[TelefonoId] INT NOT NULL,
	[SolicitudTomaMedidaId] INT NULL,
	[FechaCreacion] DATETIME NOT NULL DEFAULT GETDATE(),
	[EstadoId] INT NOT NULL,
	FOREIGN KEY (ClienteId) REFERENCES Cliente(Id),
	FOREIGN KEY (TipoComprobanteId) REFERENCES Defecto(Id),
	FOREIGN KEY (UsuarioCreacionId) REFERENCES Usuario(Id),
	FOREIGN KEY (DireccionId) REFERENCES EntidadDireccion(Id),
	FOREIGN KEY (SolicitudTomaMedidaId) REFERENCES SolicitudTomaMedida(Id),
	FOREIGN KEY (EstadoId) REFERENCES Defecto(Id),
	FOREIGN KEY (TelefonoId) REFERENCES EntidadTelefono(Id)
)
