CREATE TABLE [dbo].[DesgloseCorrederaDetalle] (
	[DesgloseCorrederaId] INT NOT NULL,
	[UnidadId] INT NOT NULL,
	[ProductoId] INT NOT NULL,
	[CantidadProducto] INT NOT NULL,
	[MedidaAnchoProducto] DECIMAL(10, 6) NOT NULL,
	[MedidaAltoProducto] DECIMAL(10, 6) NOT NULL,
	[CantidadCabezal] INT NOT NULL,
	[CantidadCabezalPendiente] INT NOT NULL,
	[MedidaCabezal] DECIMAL(10, 6) NOT NULL,
	[CantidadRiel] INT NOT NULL,
	[CantidadRielPendiente] INT NOT NULL,
	[MedidaRiel] DECIMAL(10, 6) NOT NULL,
	[CantidadLlavin] INT NOT NULL,
	[CantidadLlavinPendiente] INT NOT NULL,
	[MedidaLlavin] DECIMAL(10, 6) NOT NULL,
	[CantidadEnganche] INT NOT NULL,
	[CantidadEnganchePendiente] INT NOT NULL,
	[MedidaEnganche] DECIMAL(10, 6) NOT NULL,
	[CantidadLateral] INT NOT NULL,
	[CantidadLateralPendiente] INT NOT NULL,
	[MedidaLateral] DECIMAL(10, 6) NOT NULL,
	[CantidadVidrio] INT NOT NULL,
	[CantidadVidrioPendiente] INT NOT NULL,
	[MedidaVidrioAncho] DECIMAL(10, 6) NOT NULL,
	[MedidaVidrioAlto] DECIMAL(10, 6) NOT NULL,
	[Nota] VARCHAR(250) NOT NULL,
	[EstadoId] INT NOT NULL,
	PRIMARY KEY (DesgloseCorrederaId, ProductoId, MedidaAnchoProducto, MedidaAltoProducto),
	FOREIGN KEY (DesgloseCorrederaId) REFERENCES DesgloseCorredera(Id),
	FOREIGN KEY (ProductoId) REFERENCES Producto(Id),
	FOREIGN KEY (EstadoId) REFERENCES Registro(Id),
	FOREIGN KEY (UnidadId) REFERENCES Unidad(Id)
)
