CREATE TABLE [dbo].[Entidad] (
	[Id] INT PRIMARY KEY IDENTITY,
	[Nombre] VARCHAR(100) NOT NULL,
	[Apellido] VARCHAR(100) NOT NULL,
	[Cedula] VARCHAR(13) NOT NULL,
	[Rnc] VARCHAR(13) NOT NULL,
	[Pasaporte] VARCHAR(30) NOT NULL,
	[Correo] VARCHAR(100) NOT NULL,
	[FechaCreacion] DATETIME NOT NULL DEFAULT GETDATE(),
	[EstaActivo] BIT NOT NULL
)
